import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Building2, ClipboardList, Handshake, PackageCheck, ShieldCheck, Store, UsersRound } from "lucide-react";
import { AdminNav } from "@/components/admin-nav";
import { AppHeader } from "@/components/app-header";
import { SiteFooter } from "@/components/site-footer";
import { WRAP } from "@/lib/ui";
import { redirect } from "next/navigation";

export const metadata: Metadata = { title: "Marketplace · Administração · Distribuidora" };
const METRICS = [[Building2, "Organizações", "Demonstração", "bg-mist text-forest"], [Store, "Fornecedores", "Homologação local", "bg-sand text-terra"], [PackageCheck, "Ofertas", "Fonte autorizada", "bg-lime-soft text-forest"], [ClipboardList, "Pedidos", "Checkout simulado", "bg-blush text-plum"]] as const;
const QUEUES = [[ShieldCheck, "Homologações", "Documentos e ofertas aguardando revisão.", "/fornecedores"], [UsersRound, "Carteiras comerciais", "Atribuições de compradores e vendedores.", "/vendedores"], [Handshake, "Operação própria", "Distribuidora modelada como seller interno.", "/app/fornecedor"]] as const;

export default function MarketplaceAdminPage() {
  redirect("/admin/login");
  return <div className="min-h-dvh bg-canvas"><AppHeader theme="wine" title="Administração do marketplace" backHref="/admin" /><main className={`${WRAP} animate-page-in py-8 sm:py-12`}><AdminNav /><section className="rounded-[2rem] bg-forest p-6 text-white shadow-float sm:p-9"><p className="text-xs font-black uppercase tracking-[0.16em] text-lime">Governança comercial</p><h1 className="mt-3 max-w-3xl text-3xl font-black leading-tight tracking-tight sm:text-5xl">Uma visão única para uma operação com responsabilidades separadas.</h1><p className="mt-4 max-w-2xl text-sm font-medium leading-relaxed text-white/70">Este painel é uma demonstração local. Os indicadores abaixo não representam dados reais, GMV, receita, fornecedores ou clientes ativos.</p></section><section className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{METRICS.map(([Icon, label, detail, tone]) => <article key={label} className="rounded-3xl bg-paper p-5 shadow-card ring-1 ring-line/70"><span className={`grid size-10 place-items-center rounded-2xl ${tone}`}><Icon size={19} aria-hidden /></span><p className="mt-5 text-xs font-black uppercase tracking-[0.1em] text-muted">{label}</p><p className="mt-1 text-lg font-black tracking-tight">{detail}</p></article>)}</section><section className="mt-8 grid gap-6 lg:grid-cols-[minmax(0,1fr)_20rem]"><div className="rounded-[2rem] bg-paper p-6 shadow-card ring-1 ring-line/70"><h2 className="text-xl font-black text-forest-deep">Filas operacionais</h2><p className="mt-2 text-sm font-medium text-muted">Atalhos para os fluxos que precisam de decisão humana.</p><div className="mt-5 grid gap-3">{QUEUES.map(([Icon, title, text, href]) => <Link href={href} key={title} className="group flex items-start gap-4 rounded-2xl border border-line p-4 transition hover:bg-lime-soft"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-canvas text-forest"><Icon size={19} aria-hidden /></span><span className="min-w-0 flex-1"><strong className="block text-sm font-extrabold">{title}</strong><span className="mt-1 block text-xs font-medium leading-relaxed text-muted">{text}</span></span><ArrowRight size={16} className="mt-2 text-muted transition-transform group-hover:translate-x-1" aria-hidden /></Link>)}</div></div><aside className="rounded-[2rem] bg-wine p-6 text-white"><p className="text-xs font-black uppercase tracking-[0.14em] text-lime">Controle de acesso</p><h2 className="mt-3 text-xl font-black">Nada aqui libera produção.</h2><p className="mt-3 text-sm font-medium leading-relaxed text-white/70">RBAC, MFA, audit log persistente e revisão dupla financeira ainda precisam ser conectados a uma identidade e banco aprovados.</p><Link href="/admin/login" className="mt-6 inline-flex items-center gap-2 text-sm font-extrabold text-lime">Ver acesso administrativo <ArrowRight size={15} aria-hidden /></Link></aside></section></main><SiteFooter /></div>;
}
