import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Boxes, Search, ShieldCheck } from "lucide-react";
import { AppHeader } from "@/components/app-header";
import { SiteFooter } from "@/components/site-footer";
import { WRAP } from "@/lib/ui";

export const metadata: Metadata = { title: "Produtos autorizados · Distribuidora", description: "Catálogo próprio com produtos e ofertas de fornecedores homologados." };

export default function ProductsPage() {
  return <div className="min-h-dvh bg-canvas"><AppHeader theme="forest" title="Produtos autorizados" backHref="/" search /><main className={`${WRAP} animate-page-in py-8 sm:py-12`}><section className="rounded-[2rem] bg-forest p-7 text-white shadow-float sm:p-10"><p className="text-xs font-black uppercase tracking-[0.16em] text-lime">Catálogo B2B</p><h1 className="mt-3 max-w-3xl text-3xl font-black leading-tight tracking-tight sm:text-5xl">Produtos com origem, oferta e responsabilidade claras.</h1><p className="mt-4 max-w-2xl text-sm font-medium leading-relaxed text-white/70 sm:text-base">A busca pública será abastecida somente por produtos mestres e ofertas aprovadas da distribuidora e de fornecedores homologados.</p></section><section className="mt-8 rounded-[2rem] bg-paper p-7 shadow-card ring-1 ring-line/70 sm:p-10" aria-labelledby="empty-title"><span className="grid size-12 place-items-center rounded-2xl bg-lime-soft text-forest"><Boxes size={24} aria-hidden /></span><h2 id="empty-title" className="mt-5 text-2xl font-black tracking-tight text-forest-deep">Catálogo em preparação</h2><p className="mt-3 max-w-2xl text-sm font-medium leading-relaxed text-muted">Nenhuma oferta foi publicada nesta demonstração. Isso é intencional: não usamos preços, estoques ou produtos do comparador externo como catálogo vendável.</p><div className="mt-6 flex flex-wrap gap-2"><Link href="/fornecedores" className="inline-flex h-11 items-center gap-2 rounded-full bg-forest px-5 text-sm font-extrabold text-white hover:bg-forest-deep focus-visible:ring-4 focus-visible:ring-lime/50">Quero fornecer <ArrowRight size={15} aria-hidden /></Link><Link href="/compradores" className="inline-flex h-11 items-center gap-2 rounded-full bg-lime px-5 text-sm font-extrabold text-forest-deep hover:bg-white focus-visible:ring-4 focus-visible:ring-lime/50">Sou comprador <ArrowRight size={15} aria-hidden /></Link></div></section><section className="mt-8 grid gap-3 sm:grid-cols-3"><div className="rounded-3xl bg-paper p-5 shadow-card ring-1 ring-line/70"><Search className="text-forest" size={22} aria-hidden /><h2 className="mt-4 text-base font-extrabold">Busca interna</h2><p className="mt-2 text-sm leading-relaxed text-muted">Nome, SKU e GTIN de fontes autorizadas.</p></div><div className="rounded-3xl bg-paper p-5 shadow-card ring-1 ring-line/70"><ShieldCheck className="text-forest" size={22} aria-hidden /><h2 className="mt-4 text-base font-extrabold">Oferta homologada</h2><p className="mt-2 text-sm leading-relaxed text-muted">Preço, vigência, região e disponibilidade explícitos.</p></div><div className="rounded-3xl bg-paper p-5 shadow-card ring-1 ring-line/70"><Boxes className="text-forest" size={22} aria-hidden /><h2 className="mt-4 text-base font-extrabold">Produto mestre</h2><p className="mt-2 text-sm leading-relaxed text-muted">Vários fornecedores sem misturar estoque ou pedido.</p></div></section></main><SiteFooter /></div>;
}
