import Link from "next/link";
import { ArrowLeft, ArrowRight, BarChart3, Boxes, ClipboardList, FileText, Handshake, MapPin, ShieldCheck, ShoppingCart, UsersRound } from "lucide-react";
import { AppHeader } from "@/components/app-header";
import { SiteFooter } from "@/components/site-footer";
import { WRAP } from "@/lib/ui";

type Portal = "comprador" | "vendedor" | "fornecedor";
const content = {
  comprador: { title: "Área do comprador", eyebrow: "Operação de compras", intro: "Organize catálogo, cotações e pedidos para sua empresa.", theme: "forest" as const, cards: [[ShoppingCart, "Catálogo autorizado", "Encontre produtos e ofertas homologadas.", "/app/comprador/catalogo"], [FileText, "Cotações", "Compare respostas internas sem misturar fornecedores.", "/app/comprador/cotacoes"], [ClipboardList, "Pedidos", "Acompanhe pedidos e subpedidos por organização.", "/app/comprador/pedidos"]], links: [["/compradores", "Como funciona"]] },
  vendedor: { title: "Área do vendedor", eyebrow: "Operação comercial", intro: "Acompanhe carteira, leads e pedidos assistidos com autorização.", theme: "plum" as const, cards: [[UsersRound, "Minha carteira", "Veja somente clientes atribuídos.", "/app/vendedor/carteira"], [Handshake, "Leads e cotações", "Organize oportunidades e próximos passos.", "/app/vendedor/leads"], [BarChart3, "Comissões", "Consulte lançamentos previstos e devidos.", "/app/vendedor/comissoes"]], links: [["/vendedores", "Conhecer atuação"]] },
  fornecedor: { title: "Área do fornecedor", eyebrow: "Operação de oferta", intro: "Gerencie catálogo, ofertas e pedidos da sua organização.", theme: "terra" as const, cards: [[Boxes, "Catálogo", "Mantenha SKUs e embalagens autorizados.", "/app/fornecedor/catalogo"], [MapPin, "Regiões e prazos", "Defina onde sua operação atende.", "/app/fornecedor/operacao"], [ShieldCheck, "Homologação", "Acompanhe documentos e aprovação de ofertas.", "/app/fornecedor/homologacao"]], links: [["/fornecedores", "Ver requisitos"]] },
} as const;

export function MarketplacePortal({ portal }: { portal: Portal }) {
  const item = content[portal];
  return <div className="min-h-dvh bg-canvas"><AppHeader theme={item.theme} title={item.title} backHref="/" /><main className={`${WRAP} animate-page-in py-8 sm:py-12`}><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.14em] text-terra">{item.eyebrow}</p><h1 className="mt-2 text-3xl font-black tracking-tight text-forest-deep sm:text-4xl">{item.title}</h1><p className="mt-2 max-w-2xl text-sm font-medium leading-relaxed text-muted">{item.intro}</p></div><Link href="/" aria-label="Voltar para o início" className="hidden items-center gap-2 rounded-full bg-paper px-4 py-2 text-xs font-extrabold text-forest ring-1 ring-line hover:bg-lime-soft sm:inline-flex"><ArrowLeft size={14} aria-hidden /> Início</Link></div><div className="mt-6 rounded-3xl border border-sand bg-sand/70 p-4 text-sm font-semibold text-[#5c3a06]">Modo demonstração: a identidade própria, a organização ativa e os dados privados serão conectados após a aprovação da infraestrutura multiempresa.</div><section className="mt-8 grid gap-3 md:grid-cols-3" aria-label="Módulos do portal">{item.cards.map(([Icon, title, text, href]) => <Link href={href} key={title} className="group rounded-3xl bg-paper p-5 shadow-card ring-1 ring-line/70 transition hover:-translate-y-1 hover:shadow-float"><span className="grid size-11 place-items-center rounded-2xl bg-lime-soft text-forest"><Icon size={21} aria-hidden /></span><h2 className="mt-5 flex items-center justify-between text-base font-extrabold">{title}<ArrowRight size={16} className="text-muted transition-transform group-hover:translate-x-1" aria-hidden /></h2><p className="mt-2 text-sm font-medium leading-relaxed text-muted">{text}</p><span className="mt-5 inline-flex text-xs font-extrabold text-muted">Demonstração local</span></Link>)}</section><section className="mt-8 rounded-[2rem] bg-forest p-6 text-white sm:p-8"><p className="text-xs font-black uppercase tracking-[0.14em] text-lime">Próximo passo</p><h2 className="mt-2 text-2xl font-black tracking-tight">Conecte sua operação com segurança.</h2><p className="mt-3 max-w-2xl text-sm font-medium leading-relaxed text-white/70">Nenhuma informação deste painel é real ou compartilhada entre organizações. O portal só será ativado quando autenticação, permissões e persistência estiverem homologadas.</p><div className="mt-5 flex flex-wrap gap-2">{item.links.map(([href, label]) => <Link key={href} href={href} className="inline-flex h-11 items-center gap-2 rounded-full bg-lime px-5 text-sm font-extrabold text-forest-deep hover:bg-white focus-visible:ring-4 focus-visible:ring-lime/50">{label}<ArrowRight size={15} aria-hidden /></Link>)}</div></section></main><SiteFooter /></div>;
}
